/* Generated by .figs.mjs — six isometric figures for the Evidence section.

   One projection for all six (true 2:1 isometric, +x down-right, +y
   down-left, +z up) and one stroke language: `ev-fig-dim` is the body of
   the object, `ev-fig-key` is the part that carries the claim, `ev-fig-dash`
   is the thing that is absent, blocked, or out of scope. Reading the six in
   a row should feel like reading one set of drawings, because it is.

   Fills are none and every stroke inherits `currentColor`, so the column's
   hover state moves the whole figure without touching this file. */

export function FigSafePath() {
  return (
    <svg viewBox="0 0 300 250" fill="none" aria-hidden="true" focusable="false">
      <polygon points="103.2,75 259.1,165 196.8,201 40.9,111" className="ev-fig-dim"  />
      <polyline points="134.4,93 72.1,129" className="ev-fig-dim"  />
      <polyline points="165.6,111 103.2,147" className="ev-fig-dim"  />
      <polyline points="196.8,129 134.4,165" className="ev-fig-dim"  />
      <polyline points="227.9,147 165.6,183" className="ev-fig-dim"  />
      <polyline points="103.2,75 103.2,44.4 259.1,134.4 259.1,165" className="ev-fig-key"  />
      <polyline points="40.9,111 40.9,80.4 196.8,170.4 196.8,201" className="ev-fig-key"  />
      <polyline points="103.2,44.4 40.9,80.4" className="ev-fig-dim"  />
      <polyline points="259.1,134.4 196.8,170.4" className="ev-fig-dim"  />
      <polyline points="78.3,95.9 221.7,178.7" className="ev-fig-dash"  />
      <polyline points="188,132.6 204.6,168.1 143.1,158.5" className="ev-fig-key"  />
    </svg>
  )
}

export function FigNoTelemetry() {
  return (
    <svg viewBox="0 0 300 250" fill="none" aria-hidden="true" focusable="false">
      <polygon points="150,34.3 211.8,70 150,105.7 88.2,70" className="ev-fig-dim"  />
      <polygon points="211.8,70 211.8,138 150,173.7 150,105.7" className="ev-fig-dim"  />
      <polygon points="150,105.7 150,173.7 88.2,138 88.2,70" className="ev-fig-dim"  />
      <polygon points="150,58.4 170,70 150,81.5 130,70" className="ev-fig-key"  />
      <polyline points="163.3,77.7 194.2,95.5" className="ev-fig-dash"  />
      <polyline points="188.2,89.5 200.2,101.5" className="ev-fig-key"  />
      <polyline points="188.2,101.5 200.2,89.5" className="ev-fig-key"  />
      <polyline points="136.7,77.7 105.8,95.5" className="ev-fig-dash"  />
      <polyline points="99.8,89.5 111.8,101.5" className="ev-fig-key"  />
      <polyline points="99.8,101.5 111.8,89.5" className="ev-fig-key"  />
      <polyline points="150,54.7 150,19" className="ev-fig-dash"  />
      <polyline points="144,13 156,25" className="ev-fig-key"  />
      <polyline points="144,25 156,13" className="ev-fig-key"  />
    </svg>
  )
}

export function FigAuditTrail() {
  return (
    <svg viewBox="0 0 300 250" fill="none" aria-hidden="true" focusable="false">
      <polygon points="84,69.5 110.3,84.7 70.3,107.8 44,92.6" className="ev-fig-dim"  />
      <polygon points="110.3,84.7 110.3,92 70.3,115.1 70.3,107.8" className="ev-fig-dim"  />
      <polygon points="70.3,107.8 70.3,115.1 44,99.9 44,92.6" className="ev-fig-dim"  />
      <polyline points="80.6,78.7 94.3,86.6" className="ev-fig-key"  />
      <polyline points="69.1,85.3 78.8,90.9" className="ev-fig-dim"  />
      <polyline points="58.8,91.2 72.6,99.2" className="ev-fig-dim"  />
      <polyline points="98.8,94.9 109,100.8" className="ev-fig-key"  />
      <polyline points="81.7,104.8 91.8,110.7" className="ev-fig-key"  />
      <polyline points="103.9,97.9 86.8,107.8" className="ev-fig-key"  />
      <polygon points="120.4,90.6 146.7,105.7 106.7,128.8 80.4,113.7" className="ev-fig-dim"  />
      <polygon points="146.7,105.7 146.7,113 106.7,136.1 106.7,128.8" className="ev-fig-dim"  />
      <polygon points="106.7,128.8 106.7,136.1 80.4,120.9 80.4,113.7" className="ev-fig-dim"  />
      <polyline points="117,99.7 130.7,107.7" className="ev-fig-key"  />
      <polyline points="105.6,106.3 115.3,111.9" className="ev-fig-dim"  />
      <polyline points="95.3,112.3 109,120.2" className="ev-fig-dim"  />
      <polyline points="135.3,116 145.4,121.8" className="ev-fig-key"  />
      <polyline points="118.1,125.9 128.3,131.7" className="ev-fig-key"  />
      <polyline points="140.4,118.9 123.2,128.8" className="ev-fig-key"  />
      <polygon points="156.9,111.6 183.2,126.8 143.1,149.9 116.8,134.7" className="ev-fig-dim"  />
      <polygon points="183.2,126.8 183.2,134 143.1,157.1 143.1,149.9" className="ev-fig-dim"  />
      <polygon points="143.1,149.9 143.1,157.1 116.8,142 116.8,134.7" className="ev-fig-dim"  />
      <polyline points="153.4,120.8 167.1,128.7" className="ev-fig-key"  />
      <polyline points="142,127.4 151.7,133" className="ev-fig-dim"  />
      <polyline points="131.7,133.3 145.4,141.2" className="ev-fig-dim"  />
      <polyline points="171.7,137 181.9,142.9" className="ev-fig-key"  />
      <polyline points="154.6,146.9 164.7,152.8" className="ev-fig-key"  />
      <polyline points="176.8,139.9 159.6,149.8" className="ev-fig-key"  />
      <polygon points="193.3,132.6 219.6,147.8 179.6,170.9 153.3,155.7" className="ev-fig-dim"  />
      <polygon points="219.6,147.8 219.6,155.1 179.6,178.2 179.6,170.9" className="ev-fig-dim"  />
      <polygon points="179.6,170.9 179.6,178.2 153.3,163 153.3,155.7" className="ev-fig-dim"  />
      <polyline points="189.9,141.8 203.6,149.7" className="ev-fig-key"  />
      <polyline points="178.4,148.4 188.2,154" className="ev-fig-dim"  />
      <polyline points="168.1,154.4 181.9,162.3" className="ev-fig-dim"  />
      <polyline points="208.2,158 218.3,163.9" className="ev-fig-key"  />
      <polyline points="191,167.9 201.2,173.8" className="ev-fig-key"  />
      <polyline points="213.2,161 196.1,170.9" className="ev-fig-key"  />
      <polygon points="229.7,153.7 256,168.9 216,192 189.7,176.8" className="ev-fig-dim"  />
      <polygon points="256,168.9 256,176.1 216,199.2 216,192" className="ev-fig-dim"  />
      <polygon points="216,192 216,199.2 189.7,184 189.7,176.8" className="ev-fig-dim"  />
      <polyline points="226.3,162.8 240,170.8" className="ev-fig-key"  />
      <polyline points="214.9,169.4 224.6,175.1" className="ev-fig-dim"  />
      <polyline points="204.6,175.4 218.3,183.3" className="ev-fig-dim"  />
    </svg>
  )
}

export function FigIntrinsicBlocks() {
  return (
    <svg viewBox="0 0 300 250" fill="none" aria-hidden="true" focusable="false">
      <polygon points="206.7,73.6 223,82.9 190.5,101.6 174.3,92.3" className="ev-fig-dim"  />
      <polygon points="223,82.9 223,105.2 190.5,124 190.5,101.6" className="ev-fig-dim"  />
      <polygon points="190.5,101.6 190.5,124 174.3,114.6 174.3,92.3" className="ev-fig-dim"  />
      <polygon points="174.3,92.3 190.5,101.6 158.1,120.4 141.9,111" className="ev-fig-dim"  />
      <polygon points="190.5,101.6 190.5,124 158.1,142.7 158.1,120.4" className="ev-fig-dim"  />
      <polygon points="158.1,120.4 158.1,142.7 141.9,133.3 141.9,111" className="ev-fig-dim"  />
      <polygon points="141.9,111 158.1,120.4 125.7,139.1 109.5,129.7" className="ev-fig-dim"  />
      <polygon points="158.1,120.4 158.1,142.7 125.7,161.4 125.7,139.1" className="ev-fig-dim"  />
      <polygon points="125.7,139.1 125.7,161.4 109.5,152 109.5,129.7" className="ev-fig-dim"  />
      <polygon points="109.5,129.7 125.7,139.1 93.3,157.8 77,148.4" className="ev-fig-dim"  />
      <polygon points="125.7,139.1 125.7,161.4 93.3,180.1 93.3,157.8" className="ev-fig-dim"  />
      <polygon points="93.3,157.8 93.3,180.1 77,170.8 77,148.4" className="ev-fig-dim"  />
      <polygon points="190.5,60.6 206.7,70 174.3,88.7 158.1,79.3" className="ev-fig-dim"  />
      <polygon points="206.7,70 206.7,92.3 174.3,111 174.3,88.7" className="ev-fig-dim"  />
      <polygon points="174.3,88.7 174.3,111 158.1,101.6 158.1,79.3" className="ev-fig-dim"  />
      <polygon points="158.1,79.3 174.3,88.7 141.9,107.4 125.7,98" className="ev-fig-dim"  />
      <polygon points="174.3,88.7 174.3,111 141.9,129.7 141.9,107.4" className="ev-fig-dim"  />
      <polygon points="141.9,107.4 141.9,129.7 125.7,120.4 125.7,98" className="ev-fig-dim"  />
      <polygon points="125.7,98 141.9,107.4 109.5,126.1 93.3,116.8" className="ev-fig-dim"  />
      <polygon points="141.9,107.4 141.9,129.7 109.5,148.4 109.5,126.1" className="ev-fig-dim"  />
      <polygon points="109.5,126.1 109.5,148.4 93.3,139.1 93.3,116.8" className="ev-fig-dim"  />
      <polyline points="59.6,17.4 139.4,98.8" className="ev-fig-dash"  />
      <polyline points="139.4,98.8 109.5,42.6 72.1,3" className="ev-fig-dash"  />
      <polyline points="83.1,-1 72.1,3 76.1,13" className="ev-fig-key"  />
      <polyline points="148.1,96.6 135.7,103.8" className="ev-fig-key"  />
    </svg>
  )
}

export function FigConfigRatchet() {
  return (
    <svg viewBox="0 0 300 250" fill="none" aria-hidden="true" focusable="false">
      <polygon points="137.7,80.5 151.9,88.7 105.2,115.7 90.9,107.5" className="ev-fig-dim"  />
      <polygon points="137.7,103.9 137.7,80.5 90.9,107.5 90.9,130.9" className="ev-fig-dim"  />
      <polygon points="151.9,65.3 166.2,73.6 119.5,100.6 105.2,92.3" className="ev-fig-dim"  />
      <polygon points="151.9,88.7 151.9,65.3 105.2,92.3 105.2,115.7" className="ev-fig-dim"  />
      <polygon points="166.2,50.2 180.5,58.4 133.8,85.4 119.5,77.2" className="ev-fig-dim"  />
      <polygon points="166.2,73.6 166.2,50.2 119.5,77.2 119.5,100.6" className="ev-fig-dim"  />
      <polygon points="180.5,35 194.8,43.3 148.1,70.3 133.8,62" className="ev-fig-dim"  />
      <polygon points="180.5,58.4 180.5,35 133.8,62 133.8,85.4" className="ev-fig-dim"  />
      <polygon points="194.8,19.9 209.1,28.1 162.3,55.1 148.1,46.9" className="ev-fig-dim"  />
      <polygon points="194.8,43.3 194.8,19.9 148.1,46.9 148.1,70.3" className="ev-fig-dim"  />
      <polyline points="90.9,130.9 90.9,107.5 105.2,115.7 105.2,92.3 119.5,100.6 119.5,77.2 133.8,85.4 133.8,62 148.1,70.3 148.1,46.9 162.3,55.1 162.3,172.1 90.9,130.9" className="ev-fig-key"  />
      <polyline points="157.1,48.5 145.2,26.6 155.6,29 157.1,48.5" className="ev-fig-key"  />
      <polyline points="159.7,68.7 223.4,4.9" className="ev-fig-dash"  />
      <polyline points="212.4,2.9 223.4,4.9 221.4,15.9" className="ev-fig-key"  />
      <polyline points="153.7,62.7 165.7,74.7" className="ev-fig-key"  />
    </svg>
  )
}

export function FigHonestLimits() {
  return (
    <svg viewBox="0 0 300 250" fill="none" aria-hidden="true" focusable="false">
      <polygon points="122,69.2 201.5,115.1 110.2,167.8 30.7,121.9" className="ev-fig-dim"  />
      <polygon points="201.5,115.1 275.1,157.6 183.9,210.3 110.2,167.8" className="ev-fig-dash"  />
      <polyline points="201.5,115.1 201.5,87.9" className="ev-fig-key"  />
      <polyline points="178.7,128.2 178.7,101" className="ev-fig-key"  />
      <polyline points="155.9,141.4 155.9,114.2" className="ev-fig-key"  />
      <polyline points="133.1,154.6 133.1,127.4" className="ev-fig-key"  />
      <polyline points="110.2,167.8 110.2,140.6" className="ev-fig-key"  />
      <polyline points="201.5,87.9 110.2,140.6" className="ev-fig-key"  />
      <polyline points="201.5,99.4 110.2,152.1" className="ev-fig-key"  />
    </svg>
  )
}
